services:
  app:
    image: php:8.2-fpm
    container_name: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: honari
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  vite:
    image: node:16-alpine
    container_name: vite
    working_dir: /var/www
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
