version: '3.8'

services:
    db:
        image: mysql:5.7
        container_name: honari-db
        environment:
            MYSQL_ROOT_PASSWORD: MME13781378   # رمز عبور برای کاربر root
            MYSQL_DATABASE: honari             # نام پایگاه داده پیش‌فرض
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql

    web:
        build: .
        container_name: honari-web
        ports:
            - "8080:80"
        depends_on:
            - db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: honari-phpmyadmin
        ports:
            - "8081:80"   # پورت دسترسی به phpMyAdmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: MME13781378
        depends_on:
            - db

volumes:
    db-data:
